FROM bradrydzewski/python:2.7

RUN sudo apt-get update -qq
RUN sudo apt-get install -qq build-essential libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev python-dev libsamplerate0-dev libtag1-dev
RUN sudo apt-get install -qq python-numpy python-numpy-dev python-scipy python-pandas libsndfile1 libsndfile1-dev python-nose python-matplotlib python-sklearn python-skimage ipython python-sympy
RUN sudo apt-get install -qq sox python-pyaudio
